package frc.robot.inputs;

import org.littletonrobotics.junction.LogTable;
import org.littletonrobotics.junction.inputs.LoggableInputs;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import frc.robot.CLMath;
import frc.robot.LimelightHelpers;
import frc.robot.LimelightHelpers.PoseEstimate;

public class LimelightInputs implements LoggableInputs{
     public String name;
    public Pose2d megaTag2Pose2d;
    public double tx;
    public double ty;
    public double ta;
    public double avgTagDistance;
    public double latency;
    public Pose3d targetInCameraSpace;
    public Pose3d targetInRobotSpace;
    public int tagCount;
    public boolean isConnected;
    public double timeStampSeconds;
    public double targetTagID;

    public LimelightInputs(String name) {
        this.name = name;
    }

    public void updateInputs() {
        PoseEstimate fullPose = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(name);
        if (fullPose == null) {
            megaTag2Pose2d = null;
            avgTagDistance = 0.0;
            latency = 0.0;
        } else {
            megaTag2Pose2d = fullPose.pose;
            avgTagDistance = fullPose.avgTagDist;
            latency = fullPose.latency;
            timeStampSeconds = fullPose.timestampSeconds;
        }
        targetInCameraSpace = LimelightHelpers.getTargetPose3d_CameraSpace(name);
        targetInRobotSpace = LimelightHelpers.getTargetPose3d_RobotSpace(name);
        targetTagID = LimelightHelpers.getFiducialID(name);
        tx = LimelightHelpers.getTX(name);
        ty = LimelightHelpers.getTY(name);
        ta = LimelightHelpers.getTA(name);
        tagCount = LimelightHelpers.getTargetCount(name);
        // checks if tX exists on the Network Table by getting its value with a default
        // of NaN, and checking if it is equal to NaN
        isConnected = !Double.isNaN(LimelightHelpers.getLimelightNTTableEntry(name, "tx").getDouble(Double.NaN));
    }

    public double getClosestTagDistCameraSpace() {
        return CLMath.DistanceFromOrigin3d(targetInCameraSpace.getX(), targetInCameraSpace.getY(),
                targetInCameraSpace.getZ());
    }

    public double getClosestTagDistRobotSpace() {
        return CLMath.DistanceFromOrigin3d(targetInRobotSpace.getX(), targetInRobotSpace.getY(),
                targetInRobotSpace.getZ());
    }

    public double getClosestTagDistRobotSpace(double backup) {
        return isConnected ? getClosestTagDistRobotSpace() : backup;
    }

    // the following were auto-generated by the @AutoLog annotation
    public void toLog(LogTable table) {
        table.put("MegaTag2Pose2d", Pose2d.struct, megaTag2Pose2d);
        table.put("AvgTagDistance", avgTagDistance);
        table.put("Latency", latency);
        table.put("TimeStampSeconds", timeStampSeconds);
        table.put("tx", tx);
        table.put("ty", ty);
        table.put("ta", ta);
        table.put("TargetTagID", targetTagID);
        table.put("TargetInCameraSpace", Pose3d.struct, targetInCameraSpace);
        table.put("TargetInRobotSpace", Pose3d.struct, targetInRobotSpace);
        table.put("TagCount", tagCount);
        table.put("IsConnected", isConnected);
    }

    @Override
    public void fromLog(LogTable table) {
        megaTag2Pose2d = table.get("MegaTag2Pose2d", Pose2d.struct, (Pose2d) null); // uses a struct so that the get()
                                                                                    // method will function with a
                                                                                    // default null
        avgTagDistance = table.get("AvgTagDistance", avgTagDistance);
        timeStampSeconds = table.get("TimeStampSeconds", timeStampSeconds);
        latency = table.get("Latency", latency);
        tx = table.get("tx", tx);
        ty = table.get("ty", ty);
        ta = table.get("ta", ta);
        targetTagID = table.get("TargetTagID", targetTagID);
        targetInCameraSpace = table.get("TargetInCameraSpace", Pose3d.struct, (Pose3d) null);
        targetInRobotSpace = table.get("TargetInRobotSpace", Pose3d.struct, (Pose3d) null);
        tagCount = table.get("TagCount", tagCount);
        isConnected = table.get("IsConnected", isConnected);
    }
}
